GameSystem/Models/Msg.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameSystem.Models
{
    using System;
    using System.Collections.Generic;
    //
    using System.ComponentModel.DataAnnotations;
    public partial class Msg
    {
        public int MsgID { get; set; }
        [Display(Name = "标题:")]
        [Required(ErrorMessage = "{0}是必填项")]
        public string MsgTitle { get; set; }
        [Display(Name = "内容:")]
        [Required(ErrorMessage = "{0}是必填项")]
        public string MsgText { get; set; }
        [Display(Name = "类型:")]
        [Required(ErrorMessage = "{0}是必填项")]
        public string MsgType { get; set; }
        [Display(Name = "图片:")]
        public string MsgPhoto { get; set; }
        [Display(Name = "时间:")]
        public System.DateTime MsgTime { get; set; }
        [Display(Name = "点击数:")]
        public Nullable<int> MsgHit { get; set; }
        [Display(Name = "发布人ID:")]
        public Nullable<int> AccountID { get; set; }
    
        public virtual Account Account { get; set; }
    }
}

GameSystem/Controllers/MsgController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GameSystem.Models;

namespace GameSystem.Controllers
{
    public class MsgController : Controller
    {
        private GameDBEntities db = new GameDBEntities();

        // GET: Msg 获取信息列表
        public ActionResult Index()
        {
            var msg = db.Msg.Include(m => m.Account);
            return View(msg.ToList());
        }

        // GET: Msg/Details/5 通过信息id查询信息详情
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Msg msg = db.Msg.Find(id);
            //点击+1
            msg.MsgHit++;
            db.Entry(msg).State = EntityState.Modified;
            db.SaveChanges();
            if (msg == null)
            {
                return HttpNotFound();
            }
            return View(msg);
        }

        // GET: Msg/Create 新增信息
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Msg msg, HttpPostedFileBase photo)
        {
            if (ModelState.IsValid)
            {
                //判断用户是否登录，登录后才允许新增信息
                if (Session["Login"] != null)
                {
                    if (photo != null)
                    {
                        msg.MsgPhoto = "/img/" + photo.FileName;
                        photo.SaveAs(Server.MapPath(msg.MsgPhoto));
                    }
                    msg.MsgHit = 0; //默认点击数为0
                    msg.MsgTime = System.DateTime.Now; //信息登记时间为当前时间
                    msg.AccountID = ((Account)Session["Login"]).AccountID;//作者为当前登录用户
                    try
                    {
                        db.Msg.Add(msg);
                        db.SaveChanges();
                        return RedirectToAction("Index");//新增成功后跳转到列表页
                    }
                    catch (Exception)
                    {
                        TempData["msg"] = "新增失败!";
                    }
                }
                else TempData["msg"] = "请先登录!";
            }
            else TempData["msg"] = "表单验证失败!";
            return View(msg);
        }

        // GET: Msg/Edit/5 修改信息
        public ActionResult Edit(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            Msg msg = db.Msg.Find(id);
            if (msg == null) return HttpNotFound();
            return View(msg);
        }
        [HttpPost]
        public ActionResult Edit(Msg msg, HttpPostedFileBase photo)
        {
            if (ModelState.IsValid)
            {
                if (photo != null)
                {
                    msg.MsgPhoto = "/img/" + photo.FileName;
                    photo.SaveAs(Server.MapPath(msg.MsgPhoto));
                }
                try
                {
                    db.Entry(msg).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    TempData["msg"] = "修改失败!";
                }
            }
            else TempData["msg"] = "表单验证失败!";
            return View(msg);
        }

        // GET: Msg/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Msg msg = db.Msg.Find(id);
            if (msg == null)
            {
                return HttpNotFound();
            }
            return View(msg);
        }

        // POST: Msg/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Msg msg = db.Msg.Find(id);
            db.Msg.Remove(msg);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GameSystem/Controllers/MsgsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GameSystem.Models;

namespace GameSystem.Controllers
{
    public class MsgsController : Controller
    {
        private GameDBEntities db = new GameDBEntities();

        // GET: Msgs
        public ActionResult Index()
        {
            var msg = db.Msg.Include(m => m.Account);
            return View(msg.ToList());
        }

        // GET: Msgs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Msg msg = db.Msg.Find(id);
            if (msg == null)
            {
                return HttpNotFound();
            }
            return View(msg);
        }

        // GET: Msgs/Create
        public ActionResult Create()
        {
            ViewBag.AccountID = new SelectList(db.Account, "AccountID", "AccountName");
            return View();
        }

        // POST: Msgs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MsgID,MsgTitle,MsgText,MsgType,MsgPhoto,MsgTime,MsgHit,AccountID")] Msg msg)
        {
            if (ModelState.IsValid)
            {
                db.Msg.Add(msg);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AccountID = new SelectList(db.Account, "AccountID", "AccountName", msg.AccountID);
            return View(msg);
        }

        // GET: Msgs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Msg msg = db.Msg.Find(id);
            if (msg == null)
            {
                return HttpNotFound();
            }
            ViewBag.AccountID = new SelectList(db.Account, "AccountID", "AccountName", msg.AccountID);
            return View(msg);
        }

        // POST: Msgs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MsgID,MsgTitle,MsgText,MsgType,MsgPhoto,MsgTime,MsgHit,AccountID")] Msg msg)
        {
            if (ModelState.IsValid)
            {
                db.Entry(msg).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AccountID = new SelectList(db.Account, "AccountID", "AccountName", msg.AccountID);
            return View(msg);
        }

        // GET: Msgs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Msg msg = db.Msg.Find(id);
            if (msg == null)
            {
                return HttpNotFound();
            }
            return View(msg);
        }

        // POST: Msgs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Msg msg = db.Msg.Find(id);
            db.Msg.Remove(msg);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GameSystem/Views/Msg/Create.cshtml
@model GameSystem.Models.Msg

@{
    ViewBag.Title = "新增信息";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="content">
    <div id="clink">
        <img src="/img/icon_home2.png" />
        <a href="/Home/Index">首页</a>  >> 新增信息</a>
    </div>
    <!--新增信息-->
    <div style="color: red">@TempData["msg"]</div>
    @using (Html.BeginForm("Create", "Msg", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })<hr />
            <div class="form-group">
                @Html.LabelFor(model => model.MsgTitle, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MsgTitle, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MsgTitle, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MsgText, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.MsgText, 4,100,new { htmlAttributes = new { @class = "form-control"  } })
                    @Html.ValidationMessageFor(model => model.MsgText, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MsgType, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.MsgType, new SelectList(new[] { "新闻公告", "视频图片", "英雄档案" }), new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MsgType, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MsgPhoto, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="photo" id="photo" />
                    @Html.ValidationMessageFor(model => model.MsgPhoto, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value=" 新增 " class="btn btn-default"  style="background-color:#C9C" />
                </div>
            </div>
        </div>
    }
    <div>
        <hr /> @Html.ActionLink("返回列表", "Index")
    </div>
</div>

GameSystem/Views/Msg/Delete.cshtml
@model GameSystem.Models.Msg

@{
    ViewBag.Title = "删除信息";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="content">
    <div id="clink">
        <img src="/img/icon_home2.png" />
        <a href="/Home/Index">首页</a>  >> 删除信息</a>
    </div>
    <!--修改信息-->
    <h3>是否确认删除?</h3>
    <div>
        <dl class="dl-horizontal">
            <dt> @Html.DisplayNameFor(model => model.MsgTitle)</dt>
            <dd> @Html.DisplayFor(model => model.MsgTitle)</dd>

            <dt> @Html.DisplayNameFor(model => model.MsgText)</dt>
            <dd>@Html.DisplayFor(model => model.MsgText)</dd>

            <dt> @Html.DisplayNameFor(model => model.MsgType)</dt>
            <dd> @Html.DisplayFor(model => model.MsgType)</dd>

            <dt> @Html.DisplayNameFor(model => model.MsgPhoto)</dt>
            <dd> @Html.DisplayFor(model => model.MsgPhoto)</dd>

            <dt> @Html.DisplayNameFor(model => model.MsgTime)</dt>
            <dd>  @Html.DisplayFor(model => model.MsgTime)</dd>

            <dt> @Html.DisplayNameFor(model => model.MsgHit)</dt>
            <dd> @Html.DisplayFor(model => model.MsgHit)</dd>

            <dt>  发布人：</dt>
            <dd> @Html.DisplayFor(model => model.Account.AccountName)</dd>
        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="form-actions no-color">
                <input type="submit" value=" 确认删除 " class="btn btn-default" style="background-color:#C9C" /> 
                <hr />@Html.ActionLink("返回列表", "Index")
            </div>
        }
    </div>
</div>

GameSystem/Views/Msg/Details.cshtml
@model GameSystem.Models.Msg

@{
    ViewBag.Title = "信息详情";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="content">
    <div id="clink">
        <img src="/img/icon_home2.png" />
        <a href="/Home/Index">首页</a>  >> 信息详情</a>
    </div>
    <div id="detail">
        <div id="dTitle" style="text-align:center;font-size:20px;padding:10px;">@Html.DisplayFor(model => model.MsgTitle)</div>
        <div id="dProp" style="text-align:center;padding:10px;">
            <img src="/img/icon_author.png" />
            <span>@Html.DisplayFor(model => model.Account.AccountName)</span>
            <img src="/img/icon_clock.png" />
            <span>@Html.DisplayFor(model => model.MsgTime)</span>
            <img src="/img/icon_hit.png" />
            <span> @Html.DisplayFor(model => model.MsgHit) 次</span>
        </div>
        <div id="dImg" style="text-align:center;padding:10px;">
            <img src="@Html.DisplayFor(model => model.MsgPhoto)" />
        </div>
        <div id="dText">@Html.DisplayFor(model => model.MsgText)</div>
    </div>

</div>

GameSystem/Views/Msg/Edit.cshtml
@model GameSystem.Models.Msg

@{
    ViewBag.Title = "修改信息";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="content">
    <div id="clink">
        <img src="/img/icon_home2.png" />
        <a href="/Home/Index">首页</a>  >> 修改信息</a>
    </div>
    <!--修改信息-->
    <div style="color: red">@TempData["msg"]</div>
    @using (Html.BeginForm("Edit", "Msg", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.MsgID)
            @Html.HiddenFor(model => model.MsgPhoto)
            @Html.HiddenFor(model => model.AccountID)

            <div class="form-group">
                @Html.LabelFor(model => model.MsgTitle, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MsgTitle, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MsgTitle, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MsgText, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.MsgText, 4, 100, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MsgText, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MsgType, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.MsgType, new SelectList(new[] { "新闻公告", "视频图片", "英雄档案" }), new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MsgType, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MsgPhoto, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <img src="@Model.MsgPhoto" width="150px" height="100px" />
                    <input type="file" name="photo" id="photo" />
                    @Html.ValidationMessageFor(model => model.MsgPhoto, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MsgTime, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MsgTime, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MsgTime, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MsgHit, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MsgHit, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MsgHit, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value=" 保存 " class="btn btn-default" style="background-color:#C9C" />
                </div>
            </div>
        </div>
    }
    <div>
        <hr /> @Html.ActionLink("返回列表", "Index")
    </div>
</div>

GameSystem/Views/Msg/Index.cshtml
@model IEnumerable<GameSystem.Models.Msg>
@{
    ViewBag.Title = "信息管理";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="content">
    <div id="clink">
        <img src="/img/icon_home2.png" />
        <a href="/Home/Index">首页</a>  >>
        <a href="/Msg/Index">信息管理</a> >>
        <a href="/Msg/Create">新增信息</a>
    </div>
    <!--图文混排，信息列表-->
    <table  border="1" cellspacing="0"  >
        <tr align="center">
            <td>标题</td>
            <td>图片</td>
            <td>类型</td>
            <td>操作</td>
        </tr>
        @foreach (var item in Model)
        {
            <tr  align="center">
                <td width="300px">@item.MsgTitle</td>
                <td  width="150px"><img src="@item.MsgPhoto" style="width:100px;height:50px;" /></td>
                <td  width="150px">@item.MsgType</td>
                <td width="150px">
                    <a href="/Msg/Details/@item.MsgID" target="_blank">详情</a> |
                    <a href="/Msg/Edit/@item.MsgID">修改</a> |
                    <a href="/Msg/Delete/@item.MsgID">删除</a>
                </td>
            </tr>
        }
    </table>
</div>